trigger:
  branches:
    include:
    - main

pool:
  name: azure-keda

steps:
- checkout: self

# Kubernetes'te Docker kimlik bilgilerini tanımla
- task: Kubernetes@1
  inputs:
    connectionType: 'Kubernetes Service Connection'
    kubernetesServiceEndpoint: 'ado-agent-service-connection'
    namespace: 'default'
    command: 'apply'
    useConfigurationFile: true
    configuration: 'docker-cred-secret.yaml'

# Kaniko ile Image Oluştur ve Pushla
- task: Kubernetes@1
  inputs:
    connectionType: 'Kubernetes Service Connection'
    kubernetesServiceEndpoint: 'ado-agent-service-connection'
    namespace: 'default'
    command: 'apply'
    useConfigurationFile: true
    configuration: 'kaniko-job.yaml'
