trigger:
  branches:
    include:
    - main

pool:
  name: tzl-shrd
  demands:
    - agent.name -equals tzl-shrd-ado-865969c985-wmcx9

steps:
- checkout: self

- task: Kubernetes@1
  inputs:
    connectionType: 'Kubernetes Service Connection'
    kubernetesServiceEndpoint: 'tzlpoc'
    namespace: 'default'
    command: 'get'
    arguments: 'pods'
    secretType: 'dockerRegistry'
    containerRegistryType: 'Azure Container Registry'


