trigger:
  branches:
    include:
    - main

pool:
  name: azure-keda
  demands:
    - agent.name -equals tzl-poc-ado-778d964b76-77rbn

steps:
- checkout: self

# Kubernetes'te Docker kimlik bilgilerini tanımla
- task: Kubernetes@1
  inputs:
    connectionType: 'Kubernetes Service Connection'
    kubernetesServiceEndpoint: 'tzlpoc'
    namespace: 'default'
    command: 'get'
    useConfigurationFile: true
    arguments: 'pods'
    secretType: 'dockerRegistry'
    containerRegistryType: 'Azure Container Registry'


