apiVersion: v1
kind: Pod
metadata:
  name: kaniko
spec:
  containers:
  - name: kaniko
    image: gcr.io/kaniko-project/executor:latest
    args:
    - "--context=git://github.com/furkannakgun/kaniko-test.git"
    - "--dockerfile=Dockerfile"
    - "--destination=furkanakgun/kaniko-test:latest"
    volumeMounts:
      - name: docker-config
        mountPath: /kaniko/.docker/
  restartPolicy: Never
  volumes:
    - name: docker-config
      secret:
        secretName: docker-credentials

