apiVersion: batch/v1
kind: Job
metadata:
  name: kaniko
spec:
  template:
    spec:
      containers:
      - name: kaniko
        image: gcr.io/kaniko-project/executor:latest
        args:
        - "--context=git://https://github.com/furkannakgun/kaniko-test#refs/heads/main"
        - "--dockerfile=Dockerfile"
        - "--destination=furkanakgun/kaniko-test:latest"
        env:
        - name: DOCKER_USERNAME
          valueFrom:
            secretKeyRef:
              name: docker-credentials
              key: username
        - name: DOCKER_PASSWORD
          valueFrom:
            secretKeyRef:
              name: docker-credentials
              key: password
      restartPolicy: Never
